name: autofix.ci

on: [ push, pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo foo > foo.txt
      - uses: autofix-ci/action@commit-message
        with: 
          commit-message: "test post please ignore"
