# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  autofix:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.needs-commit }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - run: date > foo.txt
      - run: git add --all
      - run: git diff --staged --binary > .github/patch.diff
      - id: step1
        run: echo "::set-output name=needs-commit::true"
      - uses: actions/upload-artifact@v3
        with:
          name: autofix-patch
          path: patch.diff
          retention-days: 1

  commit:
    needs: autofix
    if: needs.autofix.outputs.needs-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: autofix-patch
      - name: Display structure of downloaded files
        run: ll .github/
