# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  autofix:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      needs-commit: ${{ steps.make-patch.outputs.needs-commit }}
    steps:
      - uses: actions/checkout@v3
      - run: date > foo.txt
      - uses: autofix-ci/action@main
